#!/bin/bash
set -euo pipefail

# 01_hauler_sync.sh — Pull all artifacts into the local hauler store
#
# Run as root on the admin node (nuc-00) BEFORE going airgap.
# Requires: hauler installed, ~/.bashrc.d/RGS sourced with Carbide credentials.
#
# What this does:
#   1. Logs hauler into the Carbide Secured Registry (rgcrprod.azurecr.us)
#   2. Syncs RGS products (Rancher, RKE2, NeuVector, Harvester) via --products
#   3. Dynamically builds carbide-images.yaml from the published Carbide image list
#   4. Syncs all remaining manifests (charts, images, files)
#
# Store location: $HAULER_STORE_DIR (default: /root/store — 300 GB SSD partition)
# Serve registry:   hauler store serve registry   (port 5000)
# Serve fileserver: hauler store serve fileserver  (port 8080)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_DIR="${SCRIPT_DIR}/hauler-manifests"

# ---------------------------------------------------------------------------
# Versions — update these when upgrading
# ---------------------------------------------------------------------------
RANCHER_VERSION="v2.13.3"
RKE2_VERSION="v1.35.2+rke2r1"
NEUVECTOR_VERSION="v5.4.9"
HARVESTER_VERSION="v1.4.1"
PLATFORM="linux/amd64"

CARBIDE_REGISTRY="rgcrprod.azurecr.us"
CARBIDE_IMAGES_URL="https://raw.githubusercontent.com/rancherfederal/carbide-releases/main/carbide-images.txt"
CARBIDE_KEY_URL="https://raw.githubusercontent.com/rancherfederal/carbide-releases/main/carbide-key.pub"

# ---------------------------------------------------------------------------
# Credentials — sourced from ~/.bashrc.d/RGS
# ---------------------------------------------------------------------------
if [[ "$(id -u)" -ne 0 ]]; then
  echo "ERROR: This script must be run as root."
  exit 1
fi

if [[ -z "${Carbide_Registry_Username:-}" || -z "${Carbide_Registry_Password:-}" ]]; then
  echo "ERROR: Carbide credentials not set. Source ~/.bashrc.d/RGS first."
  exit 1
fi

# ---------------------------------------------------------------------------
# Step 1 — Login to Carbide registry
# ---------------------------------------------------------------------------
echo "==> Logging into Carbide registry: ${CARBIDE_REGISTRY}"
hauler login "${CARBIDE_REGISTRY}" \
  -u "${Carbide_Registry_Username}" \
  -p "${Carbide_Registry_Password}"

# ---------------------------------------------------------------------------
# Step 2 — Sync RGS products via --products shorthand
# ---------------------------------------------------------------------------
echo "==> Syncing RGS Carbide products"
PRODUCTS="rancher=${RANCHER_VERSION},rke2=${RKE2_VERSION},neuvector=${NEUVECTOR_VERSION},harvester=${HARVESTER_VERSION}"
hauler store sync \
  --products "${PRODUCTS}" \
  --platform "${PLATFORM}" \
  --product-registry "${CARBIDE_REGISTRY}"

# ---------------------------------------------------------------------------
# Step 3 — Build carbide-images.yaml dynamically from published image list
# ---------------------------------------------------------------------------
echo "==> Fetching Carbide public key"
curl -sfL "${CARBIDE_KEY_URL}" -o "${HOME}/carbide-key.pub"

echo "==> Building ${MANIFEST_DIR}/carbide-images.yaml from Carbide image list"
CARBIDE_IMAGE_LIST=$(curl -sfL "${CARBIDE_IMAGES_URL}" | sed '/nats/d')

cat > "${MANIFEST_DIR}/carbide-images.yaml" << EOF
---
# AUTO-GENERATED by 01_hauler_sync.sh — do not edit by hand
# Source: ${CARBIDE_IMAGES_URL}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: carbide-images
  annotations:
    hauler.dev/platform: ${PLATFORM}
spec:
  images:
$(echo "${CARBIDE_IMAGE_LIST}" | sed 's/^/    - name: /')
EOF

# ---------------------------------------------------------------------------
# Step 4 — Sync all remaining manifests
# ---------------------------------------------------------------------------
echo "==> Syncing remaining manifests from ${MANIFEST_DIR}"
for MANIFEST in "${MANIFEST_DIR}"/*.yaml; do
  # Skip empty manifests (files with no images/charts/files entries)
  if grep -q 'images: \[\]\|charts: \[\]\|files: \[\]' "${MANIFEST}"; then
    echo "    Skipping (empty): $(basename "${MANIFEST}")"
    continue
  fi
  echo "    Syncing: $(basename "${MANIFEST}")"
  hauler store sync \
    --filename "${MANIFEST}" \
    --platform "${PLATFORM}" \
    --key "${HOME}/carbide-key.pub"
done

echo
echo "==> Hauler sync complete."
echo "    Store location: ${HAULER_STORE_DIR:-/root/store}"
echo
echo "    To serve the store:"
echo "      hauler store serve registry    # OCI registry  — port 5000"
echo "      hauler store serve fileserver  # HTTP files    — port 8080"
