#!/bin/bash
set -euo pipefail

# 01_hauler_sync.sh — Pull all artifacts into the local hauler store
#
# Run as root on the admin node (nuc-00) BEFORE going airgap.
# Requires: hauler installed, ~/.bashrc.d/RGS sourced with Carbide credentials.
#
# What this does:
#   1. Logs hauler into the Carbide Secured Registry (rgcrprod.azurecr.us)
#   2. Syncs each RGS product into its own store subdirectory
#   3. Dynamically builds carbide-images.yaml from the published Carbide image list
#   4. Syncs all remaining manifests, each into a store named after the manifest file
#
# Each product gets its own store under HAULER_STORE_DIR, e.g.:
#   /root/hauler/store/rancher
#   /root/hauler/store/rke2
#   /root/hauler/store/neuvector
#   /root/hauler/store/harvester
#
# After sync: push each store to its corresponding Harbor project via hauler store copy.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST_DIR="${SCRIPT_DIR}/hauler-manifests"
HAULER_STORE_DIR=/root/hauler/store

# ---------------------------------------------------------------------------
# Versions — update these when upgrading
# ---------------------------------------------------------------------------
RANCHER_VERSION="v2.13.3"
RKE2_VERSION="v1.34.4+rke2r1"
NEUVECTOR_VERSION="v5.4.9"
HARVESTER_VERSION="v1.7.1"
PLATFORM="linux/amd64"

CARBIDE_REGISTRY="rgcrprod.azurecr.us"
CARBIDE_IMAGES_URL="https://raw.githubusercontent.com/rancherfederal/carbide-releases/main/carbide-images.txt"
CARBIDE_KEY_URL="https://raw.githubusercontent.com/rancherfederal/carbide-releases/main/carbide-key.pub"

# ---------------------------------------------------------------------------
# Credentials — sourced from ~/.bashrc.d/RGS
# ---------------------------------------------------------------------------
if [[ "$(id -u)" -ne 0 ]]; then
  echo "ERROR: This script must be run as root."
  exit 1
fi

if [[ -z "${Carbide_Registry_Username:-}" || -z "${Carbide_Registry_Password:-}" ]]; then
  echo "ERROR: Carbide credentials not set. Source ~/.bashrc.d/RGS first."
  exit 1
fi

# ---------------------------------------------------------------------------
# Step 1 — Login to Carbide registry
# ---------------------------------------------------------------------------
echo "==> Logging into Carbide registry: ${CARBIDE_REGISTRY}"
hauler login "${CARBIDE_REGISTRY}" \
  -u "${Carbide_Registry_Username}" \
  -p "${Carbide_Registry_Password}"

# ---------------------------------------------------------------------------
# Step 2 — Sync each RGS product into its own store
# ---------------------------------------------------------------------------
echo "==> Syncing rancher ${RANCHER_VERSION}"
hauler store sync \
  --products "rancher=${RANCHER_VERSION}" \
  --platform "${PLATFORM}" \
  --product-registry "${CARBIDE_REGISTRY}" \
  --store "${HAULER_STORE_DIR}/rancher"

echo "==> Syncing rke2 ${RKE2_VERSION}"
hauler store sync \
  --products "rke2=${RKE2_VERSION}" \
  --platform "${PLATFORM}" \
  --product-registry "${CARBIDE_REGISTRY}" \
  --store "${HAULER_STORE_DIR}/rke2"

echo "==> Syncing neuvector ${NEUVECTOR_VERSION}"
hauler store sync \
  --products "neuvector=${NEUVECTOR_VERSION}" \
  --platform "${PLATFORM}" \
  --product-registry "${CARBIDE_REGISTRY}" \
  --store "${HAULER_STORE_DIR}/neuvector"

echo "==> Syncing harvester ${HARVESTER_VERSION}"
hauler store sync \
  --products "harvester=${HARVESTER_VERSION}" \
  --platform "${PLATFORM}" \
  --product-registry "${CARBIDE_REGISTRY}" \
  --store "${HAULER_STORE_DIR}/harvester"

# ---------------------------------------------------------------------------
# Step 3 — Build carbide-images.yaml dynamically from published image list
# ---------------------------------------------------------------------------
echo "==> Fetching Carbide public key"
curl -sfL "${CARBIDE_KEY_URL}" -o "${HOME}/carbide-key.pub"

echo "==> Building ${MANIFEST_DIR}/carbide-images.yaml from Carbide image list"
CARBIDE_IMAGE_LIST=$(curl -sfL "${CARBIDE_IMAGES_URL}" | sed '/nats/d')

cat > "${MANIFEST_DIR}/carbide-images.yaml" << EOF
---
# AUTO-GENERATED by 01_hauler_sync.sh — do not edit by hand
# Source: ${CARBIDE_IMAGES_URL}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: carbide-images
  annotations:
    hauler.dev/platform: ${PLATFORM}
spec:
  images:
$(echo "${CARBIDE_IMAGE_LIST}" | sed 's/^/    - name: /')
EOF

# ---------------------------------------------------------------------------
# Step 4 — Sync all remaining manifests
# ---------------------------------------------------------------------------
echo "==> Syncing remaining manifests from ${MANIFEST_DIR}"
for MANIFEST in "${MANIFEST_DIR}"/*.yaml; do
  # Skip empty manifests (files with no images/charts/files entries)
  if grep -q 'images: \[\]\|charts: \[\]\|files: \[\]' "${MANIFEST}"; then
    echo "    Skipping (empty): $(basename "${MANIFEST}")"
    continue
  fi
  # Derive store name from manifest filename (e.g. neuvector.yaml → .../neuvector)
  STORE_NAME="$(basename "${MANIFEST}" .yaml)"
  echo "    Syncing: $(basename "${MANIFEST}") → ${HAULER_STORE_DIR}/${STORE_NAME}"
  hauler store sync \
    --filename "${MANIFEST}" \
    --platform "${PLATFORM}" \
    --key "${HOME}/carbide-key.pub" \
    --store "${HAULER_STORE_DIR}/${STORE_NAME}"
done

echo
echo "==> Hauler sync complete."
echo "    Per-product stores under: ${HAULER_STORE_DIR}"

# ---------------------------------------------------------------------------
# Step 5 — Push stores to Harbor
#
# IMPORTANT: rke2 images are pushed WITHOUT a project prefix so they land at
#   harbor.enclave.kubernerdes.com/rancher/rke2-runtime:...
# This matches what system-default-registry: harbor.enclave.kubernerdes.com
# expects (RFC 3986 authority = hostname only, no path allowed).
#
# All other stores use a project prefix that matches Helm systemDefaultRegistry
# values in the install scripts.
# ---------------------------------------------------------------------------
HARBOR_REGISTRY="harbor.enclave.kubernerdes.com"
HARBOR_USER="admin"
HARBOR_PASS="Passw0rd01"

echo "==> Logging hauler into Harbor"
hauler login "${HARBOR_REGISTRY}" -u "${HARBOR_USER}" -p "${HARBOR_PASS}"

echo "==> Pushing rke2 → ${HARBOR_REGISTRY} (no project prefix — images land at ${HARBOR_REGISTRY}/rancher/...)"
hauler store copy \
  --store "${HAULER_STORE_DIR}/rke2" \
  "registry://${HARBOR_REGISTRY}"

echo "==> Pushing rancher → ${HARBOR_REGISTRY}/rancher"
hauler store copy \
  --store "${HAULER_STORE_DIR}/rancher" \
  "registry://${HARBOR_REGISTRY}/rancher"

echo "==> Pushing neuvector → ${HARBOR_REGISTRY}/neuvector"
hauler store copy \
  --store "${HAULER_STORE_DIR}/neuvector" \
  "registry://${HARBOR_REGISTRY}/neuvector"

echo "==> Pushing harvester → ${HARBOR_REGISTRY}/harvester"
hauler store copy \
  --store "${HAULER_STORE_DIR}/harvester" \
  "registry://${HARBOR_REGISTRY}/harvester"

echo "==> Pushing manifest stores → ${HARBOR_REGISTRY}"
for MANIFEST in "${MANIFEST_DIR}"/*.yaml; do
  STORE_NAME="$(basename "${MANIFEST}" .yaml)"
  STORE_PATH="${HAULER_STORE_DIR}/${STORE_NAME}"
  [[ -d "${STORE_PATH}" ]] || continue
  echo "    Pushing: ${STORE_NAME} → ${HARBOR_REGISTRY}/${STORE_NAME}"
  hauler store copy \
    --store "${STORE_PATH}" \
    "registry://${HARBOR_REGISTRY}/${STORE_NAME}"
done

echo
echo "==> Harbor push complete."
